### ISSUE TITLE
Hatsu can't start with PostgreSQL as database

### ISSUE THREAD

**Issue by pan93412** [importantimport/hatsu#14]
After setting up Hatsu according to <https://hatsu.cli.rs/admins/install-docker.html> and <https://hatsu.cli.rs/admins/environments.html#database_url>, it throws the following error when starting up:

```
2024-02-13 13:27:16.239Z Error: AppError { error: "Query Error: error returned from database: column \"last_refreshed_at\" is of type timestamp without time zone but expression is of type text", error_id: eb129a6b-5cc1-4b82-8350-d460617beb3b, error_details: None, status: 500, context: SpanTrace [] }
```

## Environment Variables

```
HATSU_PRIMARY_ACCOUNT=<omitted>
HATSU_LISTEN_PORT=3939
DATABASE_URL=postgresql://USER:PASSWORD@HOST:PORT/DB
HATSU_ACCESS_TOKEN=<omitted>
HATSU_DOMAIN=<omitted>
ZEABUR_WEB_URL=<omitted>
HATSU_LISTEN_HOST=0.0.0.0
```

## Workaround

Alter the type of `last_refreshed_at` in table `post` and `user` to `TEXT`.

**Comment by pan93412** [comment]
Seems like the root cause is:

https://github.com/importantimport/hatsu/blob/c7942bfdd206460b2dbc250b0acd7bfc50113d22/crates/db_migration/src/m20240131_000001_user.rs#L32

https://github.com/importantimport/hatsu/blob/c7942bfdd206460b2dbc250b0acd7bfc50113d22/crates/db_migration/src/m20240131_000003_post.rs#L23

Should it be `.string()`? cc @kwaa

**Comment by kwaa** [comment]
I'm trying to change to string (https://github.com/importantimport/hatsu/commit/0edf7e5fea7e2fd253f5314b1a3a68643ad11df4).
let me know if this issue is fixed.

**Comment by kwaa** [comment]
After testing (https://github.com/importantimport/hatsu/commit/c8ee8813c519b292ec2c8ac6b516d77c521f83f9), Hatsu currently works well with PostgreSQL database, so I'll close this issue.
