### ISSUE TITLE
relative URL without a base error

### ISSUE THREAD

**Issue by reesericci** [importantimport/hatsu#27]
Hello -

I'm running into an issue where I get this error upon startup:

```
Error: AppError { error: "relative URL without a base", error_id: 946234c9-17c1-4be0-8553-eb33aa48ae72, error_details: None, status: 500, context: SpanTrace [] }
```

I have checked that the RSS feed detection works on my site, as well as my .env file.

.env:

```
HATSU_DATABASE_URL="sqlite:///srv/hatsu/hatsu.sqlite3?mode=rwc"
HATSU_DOMAIN="fedi.place.reeseric.ci"
HATSU_LISTEN_HOST="0.0.0.0"
HATSU_LISTEN_PORT="3939"
HATSU_PRIMARY_ACCOUNT="place.reeseric.ci"
HATSU_ACCESS_TOKEN="REDACTED"
```

Full log: https://sprunge.us/GR6ko2

My site is available at https://place.reeseric.ci

**Comment by kwaa** [comment]
Hi, it looks like you're using an RSS feed: https://place.reeseric.ci/feed.xml

Hatsu doesn't have good RSS / Atom feed compatibility at the moment, I'll try to improve it later.

I'll add more tests later, and if you can, I suggest you try JSON Feed first.

**Comment by kwaa** [comment]
@reesericci Can you try `refactor/feed` branch to see if it works? On my side `parse_xml_feed` is working, but I'm not sure if everything is correctly.

**Comment by reesericci** [comment]
That fix seemed to do the trick! Thanks for the quick response once again.

**Comment by reesericci** [comment]
Actually re-opening until PR is merged
