### ISSUE TITLE
Load publish date from feed

### ISSUE THREAD

**Issue by reesericci** [importantimport/hatsu#31]
I think it would be nice if each post's publish date lined up with the publish date in the RSS feed rather than when the hatsu came online/notice the article

**Comment by kwaa** [comment]
I'm not so sure Web Signature can do that.

I'm going to replace the cron library in 0.3.0 and also allow setting the update frequency.

**Comment by kwaa** [comment]
> I'm not so sure Web Signature can do that.

Even if it could be done, I don't think faking the published date is good, so this will be wontfix.

**Comment by reesericci** [comment]
I'm not sure if this is faking the published date if it was the date the actual post was published

**Comment by kwaa** [comment]
> I'm not sure if this is faking the published date if it was the date the actual post was published

For new posts, I think it should be basically possible to synchronize time after `v0.3.0`.

For old posts, the main thing is that dates that are too old may cause compatibility issues, e.g. will some application validate this?

**Comment by kwaa** [comment]
Do you have any other questions? If not, I will close this issue.
