### ISSUE TITLE
Set icon

### ISSUE THREAD

**Issue by reesericci** [importantimport/hatsu#33]
Is it possible to set the icon of the fedi actor or pull it from the RSS feed?

![image](https://github.com/importantimport/hatsu/assets/19589006/147d16f7-db75-4b92-b24f-5051f3dca84f)

**Comment by kwaa** [comment]
Hatsu currently gets the icon from the feed.
Atom / RSS should also work, but I'm not sure how feed-rs are handled.

**Comment by reesericci** [comment]
Is it possible that it's because I use an SVG icon?

**Comment by kwaa** [comment]
> Is it possible that it's because I use an SVG icon?

Hatsu only verifies that it is a url, not the icon type. For reference, you can try accessing your actor json to see if it contains the icon

**Comment by reesericci** [comment]
Nope I don't see anything: https://fedi.place.reeseric.ci/users/place.reeseric.ci

**Comment by kwaa** [comment]
> Nope I don't see anything: [fedi.place.reeseric.ci/users/place.reeseric.ci](https://fedi.place.reeseric.ci/users/place.reeseric.ci)

I found the reason, RSS2 doesn't have an `icon`. maybe I should use the `logo` as a fallback.

https://github.com/feed-rs/feed-rs/blob/0f4d13488952b0d9f0abd140caeb30be922fcac8/feed-rs/src/parser/rss2/mod.rs#L65

**Comment by reesericci** [comment]
So I just pulled the latest version and still getting nothing

**Comment by kwaa** [comment]
> So I just pulled the latest version from main and still getting nothing

This is weird, I'll update the unit test.

**Comment by kwaa** [comment]
> So I just pulled the latest version from main and still getting nothing

It looks like the reason is that `full_update` is not updating the user info, this feature will be added later.

**Comment by kwaa** [comment]
> It looks like the reason is that `full_update` is not updating the user info, this feature will be added later.

This should be fixed by #37, but I think this part of the code is poorly written.
