### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by kwaa** [importantimport/hatsu#7]
Hatsu requires a front-end to implement [Webmention Backfeed](https://hatsu.cli.rs/users/backfeed-based-on-webmention.html).

This part is a bit more complicated, so I expect to have it done before `v1.0.0`.

Stacks:

- [Leptos](https://github.com/leptos-rs/leptos)
- ~~Style: TODO~~ ~~[Stylers](https://github.com/abishekatp/stylers)~~

Paths (temporary):

- hatsu.local/@example.com (user, `/u/example.com => /@example.com`)
- hatsu.local/@example.com/foo/bar (post, `/o/https://example.com/foo/bar => /@example.com/foo/bar`)

**Comment by kwaa** [comment]
I expect to start writing the frontend at `v0.3.0`.

It should be:

`features = ["frontend"]` - enable by default, can be disable manually when compiling locally so that it doesn't contain any frontend content

`./hatsu --frontend=false` - enable by default, disable frontend if passed `--frontend=false` as a argument

**Comment by reesericci** [comment]
Would it be possible to help design the frontend?

**Comment by reesericci** [comment]
I meant like design things page by page, not necessarily components. Also, I recently looked into using that for one of my projects and found it to be woefully incomplete unfortunately, see the [Roadmap](https://github.com/material-components/material-web/blob/main/docs/roadmap.md)

**Comment by kwaa** [comment]
> I meant like design things page by page, not necessarily components. Also, I recently looked into using that for one of my projects and found it to be woefully incomplete unfortunately, see the [Roadmap](https://github.com/material-components/material-web/blob/main/docs/roadmap.md?rgh-link-date=2024-05-13T10%3A57%3A47Z)

I welcome any help. For now, the frontend of Hatsu doesn't need to be too complex, so it should be a Mobile-first design. It's just displaying content (maybe some simple interactions and a “view original page” button)

**Comment by kwaa** [comment]
> just a quick mockup i made in a few mins, what are your thoughts?

Posts should ideally be on a separate page.

**Comment by reesericci** [comment]
could we have both a permalink page that gets rendered as a slideout frame if you click from that UI?

**Comment by kwaa** [comment]
> could we have both a permalink page that gets rendered as a drawer if you click from the UI?

My idea is still to make it as simple as possible, so we don't have to put in too much time for parts that don't matter.

**Comment by reesericci** [comment]
That makes total sense - I was just thinking from a UX perspective but simplicity is more valuable here.

I fleshed out the design a bit more:

![image](https://github.com/importantimport/hatsu/assets/19589006/89aedd20-53a8-46ad-a175-435005cb5463)


here's the figma file: https://www.figma.com/file/Tc4glSBiGnwg6crUva5uKX/hatsu?type=design&node-id=0%3A1&mode=design&t=8xFSAjkRLoe9fYWj-1

**Comment by kwaa** [comment]
For post comments / reactions, I'll use KKna directly, they're all expected to use `@material/web`, so it'll look very consistent

**Comment by reesericci** [comment]
Makes sense to em

**Comment by kwaa** [comment]
The front page should only show the Hatsu version (and optional instance info), and provide a webring-like feel to the user list on the other pages

**Comment by reesericci** [comment]
I think it would make sense to show a list of feeds though, although I do like the webring idea

**Comment by kwaa** [comment]
> I think it would make sense to show a list of feeds though. I do like the webring idea too.

The main thing I meant was to move the list of users to a separate page, with the home page only being used to display basic information.

**Comment by reesericci** [comment]
hmmm - i think the homepage being the index makes logical sense more than a separate index page

**Comment by kwaa** [comment]
I expect to write the front end in the following order:

- Home page with only basic information
- User page
- Post page
- Separate reply page (for Webmention Backfeed feature)

The other pages are low-priority.

**Comment by reesericci** [comment]
> Separate reply page (for Webmention Backfeed feature)

Can't there just be multiple h-entries on the page and link with an ID?

**Comment by kwaa** [comment]
> Can't there just be multiple h-entries on the page and link with an ID?

This means it's too complicated to implement it in KKna and SSR it.

**Comment by reesericci** [comment]
updated things a bit: 
![image](https://github.com/importantimport/hatsu/assets/19589006/fe3abf52-1ae0-436b-bfd7-e109785bd311)

**Comment by kwaa** [comment]
Here's a WIP PR: #83
